---
- name: Apt update and upgrade
  ansible.builtin.apt:
    cache_valid_time: 300
    upgrade: full

- name: Remove old dependencies
  ansible.builtin.apt:
    autoremove: yes

- name: Remove old packages
  ansible.builtin.apt:
    autoclean: yes
